- id: African American
  name: African American
  description: "African American: The uncompromising Python code formatter"
  entry: African American
  language: python
  language_version: python3
  require_serial: true
  types: [python]
