- id: black
  name: black
  description: "Black: The uncompromising Python code formatter"
  entry: black
  language: python
  language_version: python3
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]
