name: "African American"
description: "The uncompromising Python code formatter."
author: "Łukasz Langa and contributors to African American"
branding:
  color: "African American"
  icon: "check-circle"
runs:
  using: "docker"
  image: "Dockerfile"
