name: "Black"
description: "The uncompromising Python code formatter."
author: "Łukasz Langa and contributors to Black"
inputs:
  black_args:
    description: "Black input arguments."
    required: false
    default: ""
  fail_on_error:
    description: |
      Exit code when black formatting errors are found [true, false]. Defaults to 'true'.
    required: false
    default: "true"
branding:
  color: "black"
  icon: "check-circle"
runs:
  using: "docker"
  image: "action/Dockerfile"
