name: Test gh-action
on:
  push:
    paths:
      - "action/**"
    branches:
      - main
  pull_request:
    paths:
      - "action.yml"
jobs:
  test-check:
    name: runner / black-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          fail_on_error: "false"
      - name: Check if code is left untouched (not formatted)
        run: |
          changed_files=$(git status --porcelain | wc -l)
          if [[ ${changed_files} -eq 0 ]]; then
            echo "No changes detected!"
          else
            echo "Changes detected!"
            exit 1
          fi

  test-format:
    name: runner / black-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          fail_on_error: "false"
          black_args: "."
      - name: Check if formatting was successful
        run: |
          changed_files=$(git status --porcelain | wc -l)
          if [[ ${changed_files} -eq 0 ]]; then
            echo "No changes detected!"
            exit 1
          else
            echo "Changes detected!"
          fi